--obstacle_detection
--obstacle_detector_model=yolo
--yolo_detection_model_path=dependencies/models/obstacle_detection/yolo/best.pt
--nosimulator_obstacle_detection
--obstacle_detection_min_score_threshold=0.4
--obstacle_detection_gpu_index=0
###### Control config #####
--control=simulator_auto_pilot
######### CARLA settings #########
--simulator_num_people=250
--simulator_num_vehicles=20
######### Logging config #########
--log_file_name=pylot.log
--csv_log_file_name=pylot.csv
--v=1
######### Other config #########
#--visualize_rgb_camera
#--visualize_detected_obstacles
